# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d9cfec42fea83545fbf0d5600a1b918d0e09fdd8e4afc1d64a39aef5578b23dd4f6c8c9ba4f8c1786ef933c57165aff07d7febb325efe862d901838cdb45b9e2

test:
  secret_key_base: c358d7445392e67a2bc71a48a48f1f74121156bafc94dfe7c252f30591becbb99130c406e14c863fa499d34cf8bca38aa7a4fbc41b5bdbded220ede08121c645

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
